name: Scheduled Tests

on:
  schedule:
    - cron: '0 5 * * *'  # Run daily at 5:00 AM UTC
  workflow_dispatch:     # Allow manual triggers

jobs:
  e2e_tests:
    name: E2E Critical Path Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd src/web && npm ci

      - name: Install Playwright browsers
        run: cd src/web && npx playwright install --with-deps

      - name: Run E2E tests against production
        run: cd src/web && npx playwright test e2e/creator-onboarding.spec.ts e2e/content-mapping.spec.ts e2e/brand-discovery.spec.ts e2e/partnership-flow.spec.ts
        env:
          BASE_URL: 'https://engagerr.com'
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-test-results
          path: src/web/playwright-report/
          retention-days: 14

      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.19.0
        if: failure()
        with:
          slack-message: 'E2E tests failed in scheduled run! Check results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-channel: 'alerts-monitoring'
          slack-token: ${{ secrets.SLACK_WEBHOOK_URL }}

  api_health_check:
    name: API Health Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd src/backend && npm ci

      - name: Run API health checks
        run: cd src/backend && npm run test:health-check
        env:
          API_BASE_URL: 'https://api.engagerr.com'
          API_KEY: ${{ secrets.API_TEST_KEY }}

      - name: Generate health report
        run: cd src/backend && npm run generate:health-report

      - name: Upload health report
        uses: actions/upload-artifact@v3
        with:
          name: api-health-report
          path: src/backend/reports/health-report.html
          retention-days: 14

      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.19.0
        if: failure()
        with:
          slack-message: 'API health checks failed in scheduled run! Check results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-channel: 'alerts-monitoring'
          slack-token: ${{ secrets.SLACK_WEBHOOK_URL }}

  integration_checks:
    name: Platform Integration Checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd src/backend && npm ci

      - name: Run platform integration tests
        run: cd src/backend && npm run test:integrations
        env:
          YOUTUBE_TEST_TOKEN: ${{ secrets.YOUTUBE_TEST_TOKEN }}
          INSTAGRAM_TEST_TOKEN: ${{ secrets.INSTAGRAM_TEST_TOKEN }}
          TIKTOK_TEST_TOKEN: ${{ secrets.TIKTOK_TEST_TOKEN }}
          TWITTER_TEST_TOKEN: ${{ secrets.TWITTER_TEST_TOKEN }}
          STRIPE_TEST_KEY: ${{ secrets.STRIPE_TEST_KEY }}

      - name: Generate integration report
        run: cd src/backend && npm run generate:integration-report

      - name: Upload integration report
        uses: actions/upload-artifact@v3
        with:
          name: integration-report
          path: src/backend/reports/integration-report.html
          retention-days: 14

      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.19.0
        if: failure()
        with:
          slack-message: 'Platform integration checks failed in scheduled run! Check results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-channel: 'alerts-monitoring'
          slack-token: ${{ secrets.SLACK_WEBHOOK_URL }}

  weekly_performance_test:
    name: Weekly Performance Tests
    runs-on: ubuntu-latest
    if: "github.event.schedule == '0 5 * * 0'"  # Only run on Sunday at 5:00 AM UTC
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run k6 performance tests
        uses: grafana/k6-action@v0.2.0
        with:
          filename: infrastructure/performance/load-tests.js
          flags: --vus 100 --duration 5m
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          TARGET_URL: 'https://api.engagerr.com'

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: infrastructure/performance/results/
          retention-days: 30

      - name: Send performance report to Slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          slack-message: 'Weekly performance test completed. View results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-channel: 'engineering-performance'
          slack-token: ${{ secrets.SLACK_WEBHOOK_URL }}